### ISSUE TITLE
Missing initialisation for armory

### ISSUE THREAD

**Issue by FroggerHH72** [Metis-Team/mts_enhanced#100]
**Version information:**
Alle aus dem Workshop, aktuell dort bereitstehende Versionen.
Arma 3: `2.12.150301
Metis Enhanced: `Aktell aus dem Steam Workshop
CBA: `3.15.8 
ACE: `3.15.2` 
ZEN: `1.14.0` 

Hi MTS-Team,
wir würden bei der 412 gerne das Armory-Modul verwenden. 
Zur Zeit versuche ich, das lokal vorzubereiten.
Eine Datenbank habe ich eingerichtet und bekomme auch eine Verbindung.
Leider fehlt mir scheinbar der nächste Schritt, um Armory zu initialisieren.
Ich habe gesehen, dass alle Funktionen mts_armory_initialized prüfen und aussteigen, wenn die false ist.
Die ist aber durchgehend false, egal, welche Funktionen ich aufrufe.
Wenn ich die manuell auf true setze, erhalte ich mit dem Muster "this addAction ["Equipment: Flecktarn", {["FschJg Flecktarn", _this select 0] call mts_armory_fnc_openArmory}, nil, 1.5, true, true, "", "true", 5];" zwar eine Maske, aber darin tut sich ebenfalls nichts.
Mir scheint, als fehlt da ein kleiner Schritt, den ich aber leider nicht finde.

Könnt Ihr mir da ein Beispiel geben, was nach 
["armory", "armory.ini"] call mts_database_fnc_connectToDB;
aufgerufen werden muss?
Die Truppe der 412 und ich wäre sehr dankbar.

Gruß
Frogger

**Comment by PhILoXs** [comment]
Hallo @FroggerHH72,

was sagt denn die RPT aus? Kannst du die uns zur Verfügung stellen.

**Comment by FroggerHH72** [comment]
Hi @PhILoXs,
ich habe mal ein paar Dateien zusammengestellt.

Zunächst zur zweiten Frage:
Ich probiere das momentan lokal auf Windows. Start aus dem 3Den Editor im Mehrspieler-Modus.
Wenn das läuft, ist das Ziel, das in die Server-Mission der 412 zu integrieren.

Habe mir ein paar Gedanken dazu gemacht, was den außer dem rpt interessant sein könnte, da das quasi stumm ist an der Stelle. Zum schnellen Auffinden suche in den rpt nach "DB-Connection log entry Frogger".
Ich hatte bis heute erst MariaDB eingesetzt. Da habe ich dann heute einen Fehler im err-Log gesehen, der lautet
2023-06-19 21:03:04 3 [Warning] Aborted connection 3 to db: 'armory' user: 'arma' host: 'localhost' (Got an error reading communication packets)

Daraufhin habe ich dann den MySQL Community Server installiert. Der meldet dies nicht.
In beiden Versionen habe ich "set global general_log=1" gesetzt, um die Zugriffe zu sehen. Da kommt der Login und danach nichts mehr, keinerlei Abfragen auf Tabellen.

Vielleicht noch wichtig, falls da etwas falsch ist:
Ich habe extdb3 als lokales Mod im Launcher hinzugefügt, da ich nicht wüsste, wie das da anders einzufügen ist.

Gruß
Frogger

**Comment by PhILoXs** [comment]
Also ich bin schon verwundert das du ein DB Connect hinbekommen hast. Lokal auf dem Client macht armory keine Verbindung zur Datenbank auf. Das ist aktuell Hardcoded und lässt sich nur durch filepatching und das setzen des Makros " #define DEBUG_CLIENT_SERVER" erreichen.

Daher bitte ich Dich einfach auf dem Dedicated Server das ganze auszuprobieren. MySQL oder MariaDB ist dabei egal. Ich benutze immer MariaDB.

Das ganze ist mittlerweile schon ein älterer Code und war nur für ein Dedicated Server gedacht. Mittlerweise haben wir CBA Settings etc., da wäre das noch eine Überlegung das umzuschreiben. Ich wollte damit verhindern, das jeder der in Eden rumspielt, nicht andauernd fehlgeschlagene Verbindungen sieht.

**Comment by FroggerHH72** [comment]
Ich glaube, da besteht gerade ein Missverständnis. Ich habe das lokal gestartet, ja, aber als Multiplayer (MP), wobei ja ein Server lokal gestartet wird. Man kann ja grundsätzlich alle MP-Missions auch bei sich ausführen und hat dann einen Server, auf dem sich auch andere verbinden können.
Ich war soweit gekommen, dass ich in den Sources gesehen habe, dass die  Variable mts_armory_initialized auf Ihren Wert geprüft wird. Dieser ist immer false, was zu einem exitWith führt (oder irgendein ein anderer "return").
Setze ich den manuell in der Debug-Konsole auf true, dann bekomme ich auf Display46 (zumindest vermute ich, es ist das 46er) den Rahmen dargestellt. Jedoch ist dieser weiterhin ohne Funktion. Daher war meine Vermutung, dass irgendeine Initalialisierung fehlt, die Armory "starten" lässt.
Ich habe in den Sources leider keine Stelle gefunden, die den Wert von mts_armory_initialized setzt - nur verschiedene, die diesen abfragen und bei false aussteigen
Habt Ihr das Armory denn noch im Einsatz? Steht da bei Euch im init.sqf (oder einem der anderen) noch einen Aufruf nach der ExtDB-Initialisierung?

TS sehr gerne - wann passt es Dir? Ich könnte Donnerstag ab 19:30, am WE oder nächste Woche Mo, Di, Do jeweils ab 19:30.
Und auf welchem Server?

Von wegen des "umschreibens":
Ich habe parallel begonnen, etwas für das ACE-Eigenmenü zu bauen.
Das ganze wird durch Zeus-Spieler und hinterlegte UserIDs direkt innerhalb des Spiels verwaltbar sein.
Dazu schreibe ich gerne die Tage etwas mehr Infos zusammen, wenn da Interesse besteht.

**Comment by PhILoXs** [comment]
Hey,
der Check für den Server ist "isDedicated" und wird nicht true auf einem selbsgehosteten Spielerserver. Dafür wäre isServer notwendig.

Was genau bei dir Schief läuft kann ich aktuell ohne weiteres nicht sagen. Ich habe das ganze vor 2 Tagen nochmals lokal getestet und es funktioniert.

Die Variable wird in [preInit](https://github.com/Metis-Team/mts_enhanced/blob/a79e486e3d9a9e3f6055fe0b7c1ece49814437b9/addons/armory/XEH_preInit.sqf#L41) auf true gesetzt (voraussetzung ist das es ein dedizierter Server ist und eine Datenbank Verbindung herstellen kann. 

Ich würde sagen gegen 11 Uhr am Sa auf eurem TS?

**Comment by FroggerHH72** [comment]
Hi,
ok, jetzt habe ich die dedicated-Sache in Bezug auf ARMA kapiert. Wusste nicht, dass das da als anderer Softwarestart gemeint war. Ich kenne Dedicated Server sonst als Maschinen, die halt nur eine Aufgabe haben, wobei es für die Software dabei egal ist, wenn diese lokal zum Test ausgeführt wird.
Auch bei Arma kann man die Dedicated-Version so starten.
Ich habe jetzt die PBO zusammengestellt und prüfe es, aktuell startet die Anmeldung gerade noch nicht durch. 
Zeitlich komme ich vor Samstag nicht weit mit den Tests, um ein Ergebnis zu haben. Versuche es morgen Abend noch.
Aber wenn Du magst, lass uns trotzdem mal am Samstag schnacken. 
Ich habe keine Verwaltungsrechte auf unserem TS, um Dich da reinzulassen. Idee daher, über 
https://meet.jit.si/aceArmory zu treffen (läuft direkt über den Browser, ohne irgendwelche Installationen).
Der Kanal wird on demand eröffnet und anschließend vernichtet. Während der Session kann in Passwort eingestellt werden, damit keine anderen dazu können.

**Comment by PhILoXs** [comment]
Problem behoben. Es wurde ein Test Dedicated Server eingerichetet.
