### ISSUE TITLE
Common - ACE medical CBA chat commands not working

### ISSUE THREAD

**Issue by Timi007** [Metis-Team/mts_enhanced#27]
**Arma 3 Version:** `1.96` (stable)  
**Metis Enhanced Version:** `1.1.0` (stable)  
**CBA Version:** `3.13.0.191116` (stable)  
**ACE Version:** `3.13.0.45` (stable)  

**Mods:**
```
- Metis_Enhanced
- CBA_A3
- ACE
```

**Description:**
- After executing an ACE medical related chat command nothing happens.

**Steps to reproduce:**
- Login as admin
- Write "#healall" in chat
- Nothing happens

**Where did the issue occur?**
- Dedicated

**RPT log file:**
- No valuable information.

**Comment by Timi007** [comment]
ACEs Zeus module work. So maybe look into them for the new heal completely command?

**Comment by PhILoXs** [comment]
As far as i have read the Slack chat it is now _ace_medical_treatment_fnc_fullHealLocal_
