### ISSUE TITLE
Add way to remove bush

### ISSUE THREAD

**Issue by Andx667** [Metis-Team/mts_enhanced#91]
**Is your feature request related to a problem? Please describe.**
Removing Grass is great, but often bushes block the view in the same way.

**Describe the solution you'd like**
By removing bushes many positions can be utilized better. Please add an ability similar to remove grass that removes the bush im looking at.

**Describe alternatives you've considered**
This mod https://github.com/ampersand38/Brush-Clearing adds the wanted ability, but its remove grass feature is alot less useful because of the smaller grass cutter and slighty worse placement.

**Additional context**
None.

**Comment by Timi007** [comment]
Sounds good! We will work on it.
